name: finalragconverterplease
region: nyc
services:
  - name: web
    github:
      repo: machinelearningtech/FinalRAGConverterPlease
      branch: main
    dockerfile_path: backend/Dockerfile
    source_dir: backend
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: POSTGRES_SERVER
        value: 
      - key: POSTGRES_USER
        value: 
      - key: POSTGRES_PASSWORD
        value: 
      - key: POSTGRES_DB
        value: 
databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database
    version: "14"
